services:
  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    networks:
      - enrollment-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - enrollment-network

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      # Connect directly to the first galera node instead of through proxysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://galera-node1:3306/enrollment_auth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      discovery-service:
        condition: service_healthy
      galera-node1:
        condition: service_healthy
    networks:
      - enrollment-network

  course-service:
    build: ./course-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      # Connect directly to the first galera node instead of through proxysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://galera-node1:3306/enrollment_course?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      discovery-service:
        condition: service_healthy
      galera-node1:
        condition: service_healthy
    networks:
      - enrollment-network

  grade-service:
    build: ./grade-service
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      # Connect directly to the first galera node instead of through proxysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://galera-node1:3306/enrollment_grade?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      discovery-service:
        condition: service_healthy
      galera-node1:
        condition: service_healthy
    networks:
      - enrollment-network

  profile-service:
    build: ./profile-service
    ports:
      - "8085:8084"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      # Connect directly to the first galera node instead of through proxysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://galera-node1:3306/enrollment_profile?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      discovery-service:
        condition: service_healthy
      galera-node1:
        condition: service_healthy
    networks:
      - enrollment-network

  frontend-service:
    build: ./frontend-service
    ports:
      - "8084:8084"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - enrollment-network

  # Galera Cluster configuration
  galera-node1:
    image: bitnami/mariadb-galera:latest
    container_name: galera-node1  # Explicit container name
    ports:
      - "3309:3306"
    environment:
      - MARIADB_GALERA_CLUSTER_NAME=enrollment_cluster
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=enrollment
      - MARIADB_ENABLE_ROOT_FROM_ALL=yes
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backup_password
    volumes:
      - galera-node1-data:/bitnami/mariadb
      - ./galera-init:/docker-entrypoint-initdb.d
    networks:
      - enrollment-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  galera-node2:
    image: bitnami/mariadb-galera:latest
    container_name: galera-node2  # Explicit container name
    ports:
      - "3307:3306"
    environment:
      - MARIADB_GALERA_CLUSTER_NAME=enrollment_cluster
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://galera-node1
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=enrollment
      - MARIADB_ENABLE_ROOT_FROM_ALL=yes
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backup_password
    volumes:
      - galera-node2-data:/bitnami/mariadb
    networks:
      - enrollment-network
    depends_on:
      galera-node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  galera-node3:
    image: bitnami/mariadb-galera:latest
    container_name: galera-node3  # Explicit container name
    ports:
      - "3308:3306"
    environment:
      - MARIADB_GALERA_CLUSTER_NAME=enrollment_cluster
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://galera-node1
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=enrollment
      - MARIADB_ENABLE_ROOT_FROM_ALL=yes
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backup_password
    volumes:
      - galera-node3-data:/bitnami/mariadb
    networks:
      - enrollment-network
    depends_on:
      galera-node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  enrollment-network:
    driver: bridge

volumes:
  galera-node1-data:
  galera-node2-data:
  galera-node3-data:
