apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: db-secondary
  name: db-secondary
spec:
  ports:
    - name: "3309"
      port: 3309
      targetPort: 3306
  selector:
    io.kompose.service: db-secondary
