apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: db-secondary
  name: db-secondary
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-secondary
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: db-secondary
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: enrollment
            - name: MYSQL_ROOT_PASSWORD
              value: root
          image: mysql:8.0
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -u
                - root
                - -proot
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: db-secondary
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-secondary-data
      restartPolicy: Always
      volumes:
        - name: db-secondary-data
          persistentVolumeClaim:
            claimName: db-secondary-data
