apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: frontend-service
  name: frontend-service
spec:
  type: NodePort
  ports:
    - name: "8084"
      port: 8084
      targetPort: 8084
      nodePort: 30080
  selector:
    io.kompose.service: frontend-service
