apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: frontend-service
  name: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out k8s/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: frontend-service
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-service:8761/eureka/
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: library/stdiscm-enrollment-system-frontend-service:latest
          name: frontend-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 5

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 5

      restartPolicy: Always
